version: '3.4'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "admin"
      ACCEPT_EULA: "Y"
    ports:
      - "8002:1433"
    networks:
      - product-network

  product-management-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - sql-server
    networks:
      - product-network
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql-server;Database=ProductDb;User=admin;Password=admin"

networks:
  product-network:
    driver: bridge
   

